class locatorsPhase3():

    # Login Page Locators


    signInButtonXpath = "/html/body/div[1]/div/main/div/div/form/div[4]/button";
    headerYouXpath="/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/ul[1]/li[1]/a"
    cameraRollXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[1]/li[1]/ul/li[6]/a"
    cameraRollBarElementXpath="/html/body/div/div/main/div/div[3]/div/header/div/div[3]/div/button[7]/span[1]"
    uploadButtonXpath="/html/body/div/div/main/div/div[4]/div/button"
    chosePhotoOrVideoButtonXpath="/html/body/div/div/main/div/div[2]/input"
    uploadFinalButtonXpath="/html/body/div/div/main/div/div[2]/div[3]/button"
    uploadIconXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[2]/li[2]/a/i"
    profileButtonXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[2]/li[4]/div/div/div/a"
    searchInputXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[2]/li[1]/div/form/input"
    searchPeopleXpath="/html/body/div/div/main/div/button[2]"
    profileNameXpath="/html/body/div/div/main/div/div[1]/div/h2"
    profileDisplayNameXpath="/html/body/div/div/main/div/div[1]/div/h6[1]"
    followersListXpath="/html/body/div/div/main/div/div[1]/div/h6[3]"
    follwersSearchBarXpath="/html/body/div/div/main/div/div[2]/div[1]"
    changeDisplayNameXpath="/html/body/div/div/main/div/div[3]/div/div/div[4]/div/a[1]"
    changeBarXpath="/html/body/div/div/main/div/div[1]/div[4]/input"
    saveDisplayNameXpath="/html/body/div/div/main/div/div[1]/div[6]/button"
    changePasswordXpath="/html/body/div/div/main/div/div[3]/div/div/div[2]/a[1]"
    currentPasswordXpath="/html/body/div/div/main/div/div[2]/div[5]/div/div/input"
    newPasswordXpath="/html/body/div/div/main/div/div[2]/div[7]/div/div/input"
    changePasswordButtonXpath="/html/body/div/div/main/div/div[2]/div[10]/button"
    errorMessageXpath="/html/body/div[2]/table/tbody/tr/td[2]/p"
    logoutXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[2]/li[5]/a"
    loginXpath="/html/body/div/div/div/div/div[1]/div/div[1]/div/div[3]/div/ul[2]/li[2]/a"
    okGotItXpath="/html/body/div/div/main/div/div[2]/div[4]/div[2]/button"
    expectedPicTest1PlaceXplath="/html/body/div/div/main/div/div[4]/div/ul/li[2]/div/img"
    expectedPicTest2PlaceXplath = "/html/body/div/div/main/div/div[4]/div/ul/li[3]/div/img"
    photoStreamXpath="/html/body/div/div/div/div/div/div/div/div/div[3]/div/ul[1]/li[1]/ul/li[2]/a"
    camerarollPic1Xpath="/html/body/div/div/main/div/div[4]/div/div[2]/div/div[2]/div[2]/img"
    camerarollPic2Xpath = "/html/body/div/div/main/div/div[4]/div/div[2]/div/div[2]/div[3]/img"
    cameraroll="/html/body/div[1]/div/main/div/div[3]/div/header/div/div[3]/div/button[7]"